#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Devel-Symdump
Version  : 2.18
Release  : 29
URL      : https://cpan.metacpan.org/authors/id/A/AN/ANDK/Devel-Symdump-2.18.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AN/ANDK/Devel-Symdump-2.18.tar.gz
Summary  : 'dump symbol names or the symbol table'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Devel-Symdump-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
Devel::Symdump - dump symbol names or the symbol table
SYNOPSIS
# Constructor
require Devel::Symdump;
@packs = qw(some_package another_package);
$obj = Devel::Symdump->new(@packs);        # no recursion
$obj = Devel::Symdump->rnew(@packs);       # with recursion

%package dev
Summary: dev components for the perl-Devel-Symdump package.
Group: Development
Provides: perl-Devel-Symdump-devel = %{version}-%{release}
Requires: perl-Devel-Symdump = %{version}-%{release}

%description dev
dev components for the perl-Devel-Symdump package.


%package perl
Summary: perl components for the perl-Devel-Symdump package.
Group: Default
Requires: perl-Devel-Symdump = %{version}-%{release}

%description perl
perl components for the perl-Devel-Symdump package.


%prep
%setup -q -n Devel-Symdump-2.18
cd %{_builddir}/Devel-Symdump-2.18

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Devel::Symdump.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
